-- total reservations
SELECT COUNT(RESERVATION_ID) AS TOTAL_RESERVATIONS
FROM RESERVATIONS;

-- reservation status
SELECT RESERVATION_STATUS,
	COUNT(RESERVATION_STATUS) AS RES_COUNT
FROM RESERVATIONS
GROUP BY 1
ORDER BY 2 DESC;

-- marketing channel
SELECT MARKETING_CHANNEL,
	COUNT(MARKETING_CHANNEL) AS CHANNEL_COUNT
FROM RESERVATIONS
GROUP BY 1
ORDER BY 2 DESC;

-- Identify the most important cities
SELECT M.CITY,
	ROUND(SUM(R.REVENUE)::numeric,
		2) AS TOTAL_REVENUE
FROM MERCHANTS M
JOIN RESERVATIONS R ON M.MERCHANT_ID = R.MERCHANT_ID
GROUP BY M.CITY
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;